name: test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install simple-panzoom deps
        run: npm install --no-audit --no-fund
        working-directory: packages/simple-panzoom

      - name: Install sketch-ruler deps
        run: npm install --no-audit --no-fund
        working-directory: packages/sketch-ruler

      - name: Build simple-panzoom
        run: npm run build
        working-directory: packages/simple-panzoom

      - name: Build sketch-ruler
        run: npm run build
        working-directory: packages/sketch-ruler

      - name: Test simple-panzoom
        run: npm run test
        working-directory: packages/simple-panzoom

      - name: Test sketch-ruler
        run: npm run test
        working-directory: packages/sketch-ruler

      - name: Build docs
        run: npm run build
        working-directory: packages/docs

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          publish_dir: ./packages/docs/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
