name: test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'pnpm'
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Install simple-panzoom deps
        run:  pnpm i --no-frozen-lockfile
        working-directory: packages/simple-panzoom

      - name: Install sketch-ruler deps
        run: pnpm i --no-frozen-lockfile
        working-directory: packages/sketch-ruler

      - name: Build simple-panzoom
        run: pnpm run build
        working-directory: packages/simple-panzoom

      - name: Build sketch-ruler
        run: pnpm run build
        working-directory: packages/sketch-ruler

      - name: Test simple-panzoom
        run: pnpm run test
        working-directory: packages/simple-panzoom

      - name: Test sketch-ruler
        run: pnpm run test
        working-directory: packages/sketch-ruler

      - name: Build docs
        run: pnpm run build 
        working-directory: packages/docs

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          publish_dir: ./packages/docs/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
